remote_theme: pmarsceill/just-the-docs
theme: just-the-docs

title: [Svhooren]
description: [Hello everyone this is my personal page ! 
I'm a student in Geography in Brussels (Université Libre de Bruxelles).
I'll be gradutated in september 2019.
This page will be used as a blog for my Master Thesis.]
